[project]
name = "linkedin-url-hacks"
version = "0.1.0"
description = "A tiny FastAPI service that generates LinkedIn Job Search URLs with advanced filters."
readme = "README.md"
requires-python = ">=3.13"
dependencies = []
