name: Build & Deploy

on:
  workflow_dispatch:
  push:
    branches: [main]

concurrency:
  group: render-deploy-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_push_deploy:
    environment: Production
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build tester
        uses: docker/build-push-action@v5
        with:
          context: .
          target: tester
          push: false
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & push image (:latest)
        if: ${{ success() }}
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Trigger Render deploy
        if: ${{ success() }}
        run: curl -fsSL "${{ secrets.RENDER_DEPLOY_HOOK_URL }}"
